version: '3'
services:
  jupyter:
    restart: always
    build: ./jupyter_notebook
    environment:
      TWITTER_CONSUMER_KEY: ${TWITTER_CONSUMER_KEY}
      TWITTER_CONSUMER_SECRET: ${TWITTER_CONSUMER_SECRET}
      TWITTER_ACCESS_TOKEN: ${TWITTER_ACCESS_TOKEN}
      TWITTER_ACCESS_SECRET: ${TWITTER_ACCESS_SECRET}
    ports:
      - "8990:8888"
    volumes:
      - ./:/usr/src/app
    command: /usr/local/bin/jupyter notebook --port=8888 --ip=0.0.0.0 --NotebookApp.password="sha1:f217aa434731:b01a46c5ffccfc413ccffc33c802882737ac2ccd" --allow-root --NotebookApp.iopub_data_rate_limit=1.0e10
